[build]
  # Build command (optional for static deployment)
  command = "npm run fa-build"
  
  # Directory to publish (root directory contains index.html)
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  # Apply these headers to all files
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  # Fallback for SPA routing (if needed)
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # Local development settings
  command = "npm start"
  port = 3000
  publish = "."
